### ISSUE TITLE
Fail to use kinova_rqt contol robot 

### ISSUE THREAD

**Issue by Orzqq2** [Kinovarobotics/kinova-ros#300]
## Summary
I cant use this command to control jaco with error below.
## Possible issues
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_publisher/publisher_widget.py", line 105, in _update_thread_run
    message_class = roslib.message.get_message_class(base_type_str)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/message.py", line 99, in get_message_class
    cls = genpy.message.get_message_class(message_type, reload_on_error=reload_on_error)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 626, in get_message_class
    cls = _get_message_or_service_class('msg', message_type, reload_on_error=reload_on_error)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 577, in _get_message_or_service_class
    pypkg = __import__('%s.%s' % (package, type_str))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/autoware_map_msgs/msg/__init__.py", line 7, in <module>
    from ._LaneChangeRelation import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/autoware_map_msgs/msg/_LaneChangeRelation.py", line 33
    None = 0
SyntaxError: cannot assign to None
Anything that could be affected by the new feature.

**Comment by alexvannobel** [comment]
Hi @Orzqq2 ,

Sorry for the delay. Can you specify what is the exact command you try running? The error message is hard to decrypt without knowing which command you ran.

Thank you,

Alex

**Comment by felixmaisonneuve** [comment]
This thread has being inactive for over a year, I am closing this issue. If there is still a problem, please create a new issue.

Thank You
